<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MiCake.EntityFrameworkCore" Version="11.0.0-preview.2608081400" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StandardWeb.Domain\StandardWeb.Domain.csproj" />
  </ItemGroup>

</Project>
