<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MiCake.EntityFrameworkCore" Version="10.0.0-preview.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StandardWeb.Domain\StandardWeb.Domain.csproj" />
  </ItemGroup>

</Project>
