//------------------------------------------------------------------------------
// MiCake Aggregate Root Template
// Generated by MiCake Agent System
//------------------------------------------------------------------------------
// Template Variables:
// - {{Namespace}}: Root namespace (e.g., MyShop.Domain)
// - {{AggregateName}}: Name of the aggregate (e.g., Order)
// - {{IdType}}: Type of the ID (long, Guid, int, etc.)
// - {{Properties}}: List of properties
// - {{ChildEntities}}: List of child entity collections
// - {{ValueObjects}}: List of value object properties
// - {{DomainEvents}}: List of domain events
//------------------------------------------------------------------------------

using MiCake.DDD.Domain;
using {{Namespace}}.Events;
using {{Namespace}}.ValueObjects;

namespace {{Namespace}}.Aggregates;

/// <summary>
/// {{AggregateName}} aggregate root.
/// </summary>
/// <remarks>
/// Invariants:
/// {{#each Invariants}}
/// - {{this}}
/// {{/each}}
/// </remarks>
public class {{AggregateName}} : AggregateRoot<{{IdType}}>
{
    #region Properties
    
    {{#each Properties}}
    /// <summary>
    /// Gets the {{description}}.
    /// </summary>
    public {{type}} {{name}} { get; private set; }
    
    {{/each}}
    
    {{#each ChildEntities}}
    /// <summary>
    /// Gets the {{description}}.
    /// </summary>
    private readonly List<{{entityType}}> _{{camelName}} = new();
    public IReadOnlyCollection<{{entityType}}> {{name}} => _{{camelName}}.AsReadOnly();
    
    {{/each}}
    
    {{#each ValueObjects}}
    /// <summary>
    /// Gets the {{description}}.
    /// </summary>
    public {{type}} {{name}} { get; private set; } = default!;
    
    {{/each}}
    
    #endregion
    
    #region Constructors
    
    /// <summary>
    /// EF Core constructor. Do not use directly.
    /// </summary>
    protected {{AggregateName}}()
    {
    }
    
    {{#if UseStaticFactory}}
    /// <summary>
    /// Creates a new <see cref="{{AggregateName}}"/> instance.
    /// </summary>
    {{#each FactoryParameters}}
    /// <param name="{{camelName}}">{{description}}</param>
    {{/each}}
    /// <returns>A new {{AggregateName}} instance.</returns>
    public static {{AggregateName}} Create({{FactoryParameterList}})
    {
        var aggregate = new {{AggregateName}}
        {
            {{#each Properties}}
            {{name}} = {{camelName}},
            {{/each}}
        };
        
        aggregate.AddDomainEvent(new {{AggregateName}}CreatedEvent(aggregate.Id));
        
        return aggregate;
    }
    {{else}}
    /// <summary>
    /// Creates a new <see cref="{{AggregateName}}"/> instance.
    /// </summary>
    {{#each ConstructorParameters}}
    /// <param name="{{camelName}}">{{description}}</param>
    {{/each}}
    public {{AggregateName}}({{ConstructorParameterList}})
    {
        {{#each Properties}}
        {{name}} = {{camelName}};
        {{/each}}
        
        AddDomainEvent(new {{AggregateName}}CreatedEvent(Id));
    }
    {{/if}}
    
    #endregion
    
    #region Domain Methods
    
    {{#each DomainMethods}}
    /// <summary>
    /// {{description}}
    /// </summary>
    {{#each parameters}}
    /// <param name="{{name}}">{{description}}</param>
    {{/each}}
    public void {{name}}({{parameterList}})
    {
        // Validate invariants
        {{#each validations}}
        if ({{condition}})
        {
            throw new BusinessException("{{message}}");
        }
        {{/each}}
        
        // Apply changes
        {{#each changes}}
        {{this}}
        {{/each}}
        
        // Raise domain event
        AddDomainEvent(new {{eventName}}(Id{{#each eventParams}}, {{this}}{{/each}}));
    }
    
    {{/each}}
    
    #endregion
    
    #region Child Entity Management
    
    {{#each ChildEntities}}
    /// <summary>
    /// Adds a new {{entityType}} to the aggregate.
    /// </summary>
    public void Add{{entityType}}({{entityType}} item)
    {
        ArgumentNullException.ThrowIfNull(item);
        _{{camelName}}.Add(item);
    }
    
    /// <summary>
    /// Removes a {{entityType}} from the aggregate.
    /// </summary>
    public void Remove{{entityType}}({{entityType}} item)
    {
        ArgumentNullException.ThrowIfNull(item);
        _{{camelName}}.Remove(item);
    }
    
    {{/each}}
    
    #endregion
}

//------------------------------------------------------------------------------
// EXAMPLE: Filled template for Order aggregate
//------------------------------------------------------------------------------
/*
using MiCake.DDD.Domain;
using MyShop.Domain.Events;
using MyShop.Domain.ValueObjects;

namespace MyShop.Domain.Aggregates;

/// <summary>
/// Order aggregate root.
/// </summary>
/// <remarks>
/// Invariants:
/// - Order must have at least one item
/// - Total amount cannot be negative
/// </remarks>
public class Order : AggregateRoot<long>
{
    #region Properties
    
    /// <summary>
    /// Gets the customer identifier.
    /// </summary>
    public long CustomerId { get; private set; }
    
    /// <summary>
    /// Gets the order date.
    /// </summary>
    public DateTime OrderDate { get; private set; }
    
    /// <summary>
    /// Gets the order status.
    /// </summary>
    public OrderStatus Status { get; private set; }
    
    /// <summary>
    /// Gets the order items.
    /// </summary>
    private readonly List<OrderItem> _items = new();
    public IReadOnlyCollection<OrderItem> Items => _items.AsReadOnly();
    
    /// <summary>
    /// Gets the total amount.
    /// </summary>
    public Money TotalAmount { get; private set; } = default!;
    
    #endregion
    
    #region Constructors
    
    protected Order()
    {
    }
    
    public static Order Create(long customerId, Money initialAmount)
    {
        var order = new Order
        {
            CustomerId = customerId,
            OrderDate = DateTime.UtcNow,
            Status = OrderStatus.Pending,
            TotalAmount = initialAmount
        };
        
        order.AddDomainEvent(new OrderCreatedEvent(order.Id));
        
        return order;
    }
    
    #endregion
    
    #region Domain Methods
    
    public void AddItem(OrderItem item)
    {
        ArgumentNullException.ThrowIfNull(item);
        _items.Add(item);
        RecalculateTotal();
    }
    
    public void Confirm()
    {
        if (Status != OrderStatus.Pending)
        {
            throw new BusinessException("Only pending orders can be confirmed.");
        }
        
        if (!_items.Any())
        {
            throw new BusinessException("Order must have at least one item.");
        }
        
        Status = OrderStatus.Confirmed;
        AddDomainEvent(new OrderConfirmedEvent(Id));
    }
    
    private void RecalculateTotal()
    {
        var total = _items.Sum(x => x.Price.Amount * x.Quantity);
        TotalAmount = new Money(total, TotalAmount.Currency);
    }
    
    #endregion
}
*/
