//------------------------------------------------------------------------------
// MiCake Domain Event Template
// Generated by MiCake Agent System
//------------------------------------------------------------------------------
// Template Variables:
// - {{Namespace}}: Root namespace
// - {{EventName}}: Name of the domain event (should be past-tense)
// - {{AggregateName}}: Name of the aggregate that raises this event
// - {{Properties}}: Additional properties of the event
//------------------------------------------------------------------------------

using MiCake.DDD.Domain;

namespace {{Namespace}}.Events;

/// <summary>
/// Domain event raised when {{EventDescription}}.
/// </summary>
/// <remarks>
/// Domain events are raised by aggregates and handled asynchronously.
/// They represent something that has already happened in the domain.
/// </remarks>
public sealed class {{EventName}} : DomainEvent
{
    /// <summary>
    /// Gets the ID of the {{AggregateName}} that raised this event.
    /// </summary>
    public {{AggregateIdType}} {{AggregateName}}Id { get; }
    
    {{#each Properties}}
    /// <summary>
    /// Gets {{description}}.
    /// </summary>
    public {{type}} {{name}} { get; }
    
    {{/each}}
    
    /// <summary>
    /// Creates a new <see cref="{{EventName}}"/> instance.
    /// </summary>
    /// <param name="{{aggregateCamelName}}Id">The aggregate ID.</param>
    {{#each Properties}}
    /// <param name="{{camelName}}">{{description}}</param>
    {{/each}}
    public {{EventName}}(
        {{AggregateIdType}} {{aggregateCamelName}}Id{{#if Properties}},{{/if}}
        {{#each Properties}}
        {{type}} {{camelName}}{{#unless @last}},{{/unless}}
        {{/each}})
    {
        {{AggregateName}}Id = {{aggregateCamelName}}Id;
        {{#each Properties}}
        {{name}} = {{camelName}};
        {{/each}}
    }
}

//------------------------------------------------------------------------------
// Domain Event Handler Template
//------------------------------------------------------------------------------

namespace {{Namespace}}.EventHandlers;

/// <summary>
/// Handles <see cref="{{EventName}}"/>.
/// </summary>
public class {{EventName}}Handler : IDomainEventHandler<{{EventName}}>
{
    private readonly ILogger<{{EventName}}Handler> _logger;
    {{#each Dependencies}}
    private readonly {{type}} _{{camelName}};
    {{/each}}
    
    public {{EventName}}Handler(
        ILogger<{{EventName}}Handler> logger{{#if Dependencies}},{{/if}}
        {{#each Dependencies}}
        {{type}} {{camelName}}{{#unless @last}},{{/unless}}
        {{/each}})
    {
        _logger = logger;
        {{#each Dependencies}}
        _{{camelName}} = {{camelName}};
        {{/each}}
    }
    
    public async Task HandleAsync({{EventName}} domainEvent, CancellationToken cancellationToken = default)
    {
        _logger.LogInformation(
            "Handling {EventName} for {{AggregateName}} {Id}",
            nameof({{EventName}}),
            domainEvent.{{AggregateName}}Id);
        
        // TODO: Implement event handling logic
        {{#each HandlerActions}}
        // {{description}}
        {{/each}}
        
        await Task.CompletedTask;
    }
}

//------------------------------------------------------------------------------
// EXAMPLES
//------------------------------------------------------------------------------

/*
// Example 1: OrderCreatedEvent
public sealed class OrderCreatedEvent : DomainEvent
{
    public long OrderId { get; }
    public long CustomerId { get; }
    public DateTime OrderDate { get; }
    
    public OrderCreatedEvent(long orderId, long customerId, DateTime orderDate)
    {
        OrderId = orderId;
        CustomerId = customerId;
        OrderDate = orderDate;
    }
}

// Handler for OrderCreatedEvent
public class OrderCreatedEventHandler : IDomainEventHandler<OrderCreatedEvent>
{
    private readonly ILogger<OrderCreatedEventHandler> _logger;
    private readonly IEmailService _emailService;
    private readonly IInventoryService _inventoryService;
    
    public OrderCreatedEventHandler(
        ILogger<OrderCreatedEventHandler> logger,
        IEmailService emailService,
        IInventoryService inventoryService)
    {
        _logger = logger;
        _emailService = emailService;
        _inventoryService = inventoryService;
    }
    
    public async Task HandleAsync(OrderCreatedEvent domainEvent, CancellationToken cancellationToken = default)
    {
        _logger.LogInformation("Processing new order {OrderId}", domainEvent.OrderId);
        
        // Send confirmation email
        await _emailService.SendOrderConfirmationAsync(domainEvent.OrderId, cancellationToken);
        
        // Reserve inventory
        await _inventoryService.ReserveForOrderAsync(domainEvent.OrderId, cancellationToken);
    }
}

// Example 2: OrderStatusChangedEvent
public sealed class OrderStatusChangedEvent : DomainEvent
{
    public long OrderId { get; }
    public OrderStatus OldStatus { get; }
    public OrderStatus NewStatus { get; }
    public DateTime ChangedAt { get; }
    
    public OrderStatusChangedEvent(
        long orderId, 
        OrderStatus oldStatus, 
        OrderStatus newStatus)
    {
        OrderId = orderId;
        OldStatus = oldStatus;
        NewStatus = newStatus;
        ChangedAt = DateTime.UtcNow;
    }
}

// Example 3: Event with value object
public sealed class OrderItemAddedEvent : DomainEvent
{
    public long OrderId { get; }
    public long ProductId { get; }
    public int Quantity { get; }
    public Money Price { get; }
    
    public OrderItemAddedEvent(
        long orderId,
        long productId,
        int quantity,
        Money price)
    {
        OrderId = orderId;
        ProductId = productId;
        Quantity = quantity;
        Price = price;
    }
}
*/

//------------------------------------------------------------------------------
// EVENT NAMING CONVENTIONS
//------------------------------------------------------------------------------
/*
[YES] Good event names (past tense - something happened):
- OrderCreatedEvent
- OrderConfirmedEvent
- PaymentReceivedEvent
- ItemAddedToCartEvent
- UserRegisteredEvent
- PasswordChangedEvent

[NO] Bad event names (avoid these patterns):
- CreateOrderEvent (imperative - sounds like a command)
- OrderEvent (too generic)
- OrderCreated (missing Event suffix for clarity)
- OrderStatusEvent (doesn't describe what happened)

Naming pattern:
{Aggregate}{Action}Event
- Aggregate: The aggregate root that raised the event
- Action: Past-tense verb describing what happened
- Event: Suffix for clarity

Examples:
- Order + Created = OrderCreatedEvent
- Order + Confirmed = OrderConfirmedEvent
- Order + Cancelled = OrderCancelledEvent
- Order + ItemAdded = OrderItemAddedEvent
*/
