//------------------------------------------------------------------------------
// MiCake Entity Template
// Generated by MiCake Agent System
//------------------------------------------------------------------------------
// Template Variables:
// - {{Namespace}}: Root namespace
// - {{EntityName}}: Name of the entity
// - {{IdType}}: Type of the ID (int for child entities is common)
// - {{Properties}}: List of properties
// - {{ParentAggregate}}: Name of the parent aggregate (for child entities)
//------------------------------------------------------------------------------

using MiCake.DDD.Domain;

namespace {{Namespace}}.Aggregates;

/// <summary>
/// {{EntityName}} entity.
/// {{#if IsChildEntity}}
/// Child entity of <see cref="{{ParentAggregate}}"/>.
/// {{/if}}
/// </summary>
public class {{EntityName}} : Entity<{{IdType}}>
{
    #region Properties
    
    {{#each Properties}}
    /// <summary>
    /// Gets {{#if description}}the {{description}}{{else}}or sets {{name}}{{/if}}.
    /// </summary>
    public {{type}} {{name}} { get; private set; }{{#if hasDefault}} = {{default}};{{/if}}
    
    {{/each}}
    
    {{#if IsChildEntity}}
    /// <summary>
    /// Gets the parent {{ParentAggregate}} identifier.
    /// </summary>
    public {{ParentIdType}} {{ParentAggregate}}Id { get; private set; }
    {{/if}}
    
    #endregion
    
    #region Constructors
    
    /// <summary>
    /// EF Core constructor. Do not use directly.
    /// </summary>
    protected {{EntityName}}()
    {
    }
    
    {{#if UseStaticFactory}}
    /// <summary>
    /// Creates a new <see cref="{{EntityName}}"/> instance.
    /// </summary>
    public static {{EntityName}} Create({{FactoryParameterList}})
    {
        return new {{EntityName}}
        {
            {{#each Properties}}
            {{name}} = {{camelName}},
            {{/each}}
        };
    }
    {{else}}
    /// <summary>
    /// Creates a new <see cref="{{EntityName}}"/> instance.
    /// </summary>
    public {{EntityName}}({{ConstructorParameterList}})
    {
        {{#each Properties}}
        {{name}} = {{camelName}};
        {{/each}}
    }
    {{/if}}
    
    #endregion
    
    #region Domain Methods
    
    {{#each DomainMethods}}
    /// <summary>
    /// {{description}}
    /// </summary>
    public void {{name}}({{parameterList}})
    {
        {{#each validations}}
        if ({{condition}})
        {
            throw new ArgumentException("{{message}}");
        }
        {{/each}}
        
        {{#each changes}}
        {{this}}
        {{/each}}
    }
    
    {{/each}}
    
    #endregion
}

//------------------------------------------------------------------------------
// EXAMPLE: OrderItem entity (child of Order aggregate)
//------------------------------------------------------------------------------
/*
using MiCake.DDD.Domain;
using MyShop.Domain.ValueObjects;

namespace MyShop.Domain.Aggregates;

/// <summary>
/// OrderItem entity.
/// Child entity of <see cref="Order"/>.
/// </summary>
public class OrderItem : Entity<int>
{
    #region Properties
    
    /// <summary>
    /// Gets the product identifier.
    /// </summary>
    public long ProductId { get; private set; }
    
    /// <summary>
    /// Gets the product name (snapshot).
    /// </summary>
    public string ProductName { get; private set; } = string.Empty;
    
    /// <summary>
    /// Gets the unit price.
    /// </summary>
    public Money Price { get; private set; } = default!;
    
    /// <summary>
    /// Gets the quantity.
    /// </summary>
    public int Quantity { get; private set; }
    
    /// <summary>
    /// Gets the parent Order identifier.
    /// </summary>
    public long OrderId { get; private set; }
    
    #endregion
    
    #region Constructors
    
    protected OrderItem()
    {
    }
    
    public static OrderItem Create(long productId, string productName, Money price, int quantity)
    {
        if (quantity <= 0)
        {
            throw new ArgumentException("Quantity must be positive.", nameof(quantity));
        }
        
        return new OrderItem
        {
            ProductId = productId,
            ProductName = productName,
            Price = price,
            Quantity = quantity
        };
    }
    
    #endregion
    
    #region Domain Methods
    
    /// <summary>
    /// Updates the quantity.
    /// </summary>
    public void UpdateQuantity(int newQuantity)
    {
        if (newQuantity <= 0)
        {
            throw new ArgumentException("Quantity must be positive.", nameof(newQuantity));
        }
        
        Quantity = newQuantity;
    }
    
    /// <summary>
    /// Gets the line total.
    /// </summary>
    public decimal GetLineTotal() => Price.Amount * Quantity;
    
    #endregion
}
*/
