<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RBACWeb.Domain\RBACWeb.Domain.csproj" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="MiCake.EntityFrameworkCore" Version="11.0.0-preview.2608081400" />
  </ItemGroup>

</Project>
